#!/usr/bin/env bash

# Vérifier si l'adresse IP est fournie en argument
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Pinger l'adresse IP 5 fois
ping -c 5 "$1"
