#!/usr/bin/env bash

# Ce script vérifie si une adresse IP est fournie en argument et envoie un ping 5 fois pour vérifier la connectivité réseau.
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi
# Envoyer un ping 5 fois à l'adresse IP spécifiée
ping -c 5 "$1"
