#!/usr/bin/env bash
# Script to configure an Ubuntu server with specific IP addresses
# - Changes localhost to resolve to 127.0.0.2
# - Changes facebook.com to resolve to 8.8.8.8
# Create a new hosts file
cp /etc/hosts ~/hosts.new
# Update the localhost entry
sed -i 's/127[.][0-9.]*[[:space:]]localhost$/127.0.0.2 localhost/' ~/hosts.new
grep -q "127.0.0.2 localhost" ~/hosts.new || echo "127.0.0.2 localhost" >> ~/hosts.new
# Update the facebook.com entry
sed -i '/facebook\.com$/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
# Replace the original hosts file
cp -f ~/hosts.new /etc/hosts
# Clean up
rm -f ~/hosts.new
