#!/usr/bin/env bash
# configure les adresses IP de localhost et de facebook.com dans le fichier /etc/hosts.

# Vérifie si le script est exécuté en tant que root
if [ "$EUID" -ne 0 ]; then
  echo "Veuillez exécuter en tant que root"
  exit 1
fi

# Sauvegarde du fichier /etc/hosts d'origine
cp /etc/hosts /etc/hosts.bak

# Mise à jour du fichier /etc/hosts avec les nouvelles adresses IP
echo "Mise à jour du fichier /etc/hosts..."
sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
sed -i '/8.8.8.8\s\+facebook.com/d' /etc/hosts

# Ajoute les nouvelles correspondances d'IP
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Affiche le fichier hosts mis à jour
echo "Fichier /etc/hosts mis à jour :"
cat /etc/hosts

echo "Les adresses IP ont été mises à jour avec succès !"
