#!/usr/bin/env bash
# Ce script écoute sur le port 98 en utilisant Netcat (nc) sur localhost.

# Vérifie si le script est exécuté en tant que root
if [ "$EUID" -ne 0 ]; then
  echo "Veuillez exécuter en tant que root"
  exit 1
fi

# Utilise Netcat pour écouter sur le port 98 sur localhost
echo "Écoute sur le port 98 de localhost..."
nc -lvk 127.0.0.1 98
